### ISSUE TITLE
Unreliable timing measure

### ISSUE THREAD

**Issue by elfmimi** [smart-leds-rs/ws2812-nop-samd21#2]
I tried this crate with Adafruit QT Py which has WS2812-2020 onboard. and its operation is somewhat unstable.
When on the stable channel delay() or nop() does not get inline expansion and hence unsuitable for timing adjustment.

Here is what worked well for me. Of course it only works fine when it is optimized (release build) .
```Rust
    fn write_byte(&mut self, data: u8) {
        let mut bitmask: u8 = 0x80;
        while bitmask != 0 {
            self.pin.set_high().ok();
            self.pin.set_high().ok();
            self.pin.set_high().ok();
            if data & bitmask != 0 {
                self.pin.set_high().ok();
                self.pin.set_high().ok();
                self.pin.set_high().ok();
            } else {
                self.pin.set_low().ok();
                self.pin.set_low().ok();
                self.pin.set_low().ok();
            }
            self.pin.set_low().ok();
            self.pin.set_low().ok();
            self.pin.set_low().ok();
            bitmask >>= 1;
        }
    }
```

**Comment by david-sawatzke** [comment]
@sajattack I think the only way to avoid breakages like these is to integrate closer with the chip-specific hals, with something that's less fiddly, like using timer outputs

**Comment by sajattack** [comment]
Yeah the nop was always a little half-baked.

**Comment by sajattack** [comment]
I'm fine if you want to archive and yank these @david-sawatzke

**Comment by david-sawatzke** [comment]
Ok, done @sajattack. Thanks for the contribution @elfmimi, but as it stands, this approach is too unstable to use.
